# ROS2 Message for the media pipe pose detection node
# contains the 3d position of each detected body landmark
# in the camera frame
std_msgs/Header header

geometry_msgs/Point nose
geometry_msgs/Point left_eye_inner
geometry_msgs/Point left_eye
geometry_msgs/Point left_eye_outer
geometry_msgs/Point right_eye_inner
geometry_msgs/Point right_eye
geometry_msgs/Point right_eye_outer
geometry_msgs/Point left_ear
geometry_msgs/Point right_ear
geometry_msgs/Point mouth_left
geometry_msgs/Point mouth_right
geometry_msgs/Point left_shoulder
geometry_msgs/Point right_shoulder
geometry_msgs/Point left_elbow
geometry_msgs/Point right_elbow
geometry_msgs/Point left_wrist
geometry_msgs/Point right_wrist
geometry_msgs/Point left_pinky
geometry_msgs/Point right_pinky
geometry_msgs/Point left_index
geometry_msgs/Point right_index
geometry_msgs/Point left_thumb
geometry_msgs/Point right_thumb
geometry_msgs/Point left_hip
geometry_msgs/Point right_hip
geometry_msgs/Point left_knee
geometry_msgs/Point right_knee
geometry_msgs/Point left_ankle
geometry_msgs/Point right_ankle
geometry_msgs/Point left_heel
geometry_msgs/Point right_heel
geometry_msgs/Point left_foot_index
geometry_msgs/Point right_foot_index
