# Interface for the Bezier fitting service
# the request contains an array of poses
# and the response contains and array of position curves
# and an array of orientation curves

geometry_msgs/PoseArray pose_trajectory
---
roboasset_msgs/FittedBezierSpline fitted_spline
