# Start recording a given topic

# filename for the rosbag that will be created
string filename

# a list of topic names to record
string[] topic_names

# the event that will trigger the start of the recording
string start_event

# the event that will trigger the stop of the recording
string stop_event

# Maximum time to wait for the start event to be triggered
float32 timeout 0.0

# Maximum time to wait for the stop event to be triggered
float32 duration 60.0

---
bool success
string info
